version: '3.8'

services:
  api:
    build: ./
    ports:
    - 5000:5000
    environment:
      SECRET_FOR_REFRESH: DebugSecret
      CONNECTION_STRING: postgresql+psycopg2://postgres:Password123@debug_db:5432/schedule_api_debug_database
    # entrypoint: bash -c 'flask db init && flask db migrate -m "Initial migration." && flask db upgrade'
  refresh_invoker:
    build: ./refresh_invoker
  proxy:
    build: ./proxy
    ports:
    - 5001:5001


  debug_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: schedule_api_debug_database
configs:
  my_config:
    file: ./migration.sh