iabo_01_19_lessons = [
    {
        "day_of_week": 1,
        "week": 1,
        "is_usual_place": True,
        "id": 67,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [],
        "lesson_type": None,
        "discipline": {"name": "Военная", "id": 16},
        "room": None,
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 2,
        "week": 1,
        "is_usual_place": True,
        "id": 68,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Макаров В.А.", "id": 31}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Проектирование и разработка автоматизированных систем реального времени",
            "id": 17,
        },
        "room": {
            "name": "А-214",
            "id": 19,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 2,
        "week": 2,
        "is_usual_place": True,
        "id": 69,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Петухов А.М.", "id": 32}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Программирование промышленных систем автоматизации",
            "id": 18,
        },
        "room": {
            "name": "А-214",
            "id": 19,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 2,
        "week": 1,
        "is_usual_place": True,
        "id": 70,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Петухов А.М.", "id": 32}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Программирование промышленных систем автоматизации",
            "id": 18,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 2,
        "week": 2,
        "is_usual_place": True,
        "id": 71,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Петухов А.М.", "id": 32}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Программирование промышленных систем автоматизации",
            "id": 18,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 2,
        "week": 1,
        "is_usual_place": True,
        "id": 72,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Володина А.М.", "id": 30}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Проектирование и разработка автоматизированных систем реального времени",
            "id": 17,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 2,
        "week": 2,
        "is_usual_place": True,
        "id": 73,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Володина А.М.", "id": 30}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Проектирование и разработка автоматизированных систем реального времени",
            "id": 17,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 2,
        "week": 1,
        "is_usual_place": True,
        "id": 74,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Петухов А.М.", "id": 32}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Программирование промышленных систем автоматизации",
            "id": 18,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [1],
        "every_week": False,
    },
    {
        "day_of_week": 2,
        "week": 2,
        "is_usual_place": True,
        "id": 75,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Огорельцев Р.М.", "id": 33}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Программирование промышленных систем автоматизации",
            "id": 18,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 2,
        "week": 1,
        "is_usual_place": True,
        "id": 76,
        "call": {"call_num": 5, "begin_time": "16:20", "end_time": "17:50", "id": 5},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Петухов А.М.", "id": 32}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Программирование промышленных систем автоматизации",
            "id": 18,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [1],
        "every_week": False,
    },
    {
        "day_of_week": 2,
        "week": 2,
        "is_usual_place": True,
        "id": 77,
        "call": {"call_num": 5, "begin_time": "16:20", "end_time": "17:50", "id": 5},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Огорельцев Р.М.", "id": 33}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Программирование промышленных систем автоматизации",
            "id": 18,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 2,
        "week": 1,
        "is_usual_place": True,
        "id": 78,
        "call": {"call_num": 6, "begin_time": "18:00", "end_time": "19:30", "id": 6},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Мильчакова Н.Е.", "id": 34}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {"name": "Дизайн интерфейсов систем управления", "id": 19},
        "room": {
            "name": "А-15",
            "id": 22,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 2,
        "week": 2,
        "is_usual_place": True,
        "id": 79,
        "call": {"call_num": 6, "begin_time": "18:00", "end_time": "19:30", "id": 6},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Чижиков В.И.", "id": 35}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {"name": "Моделирование автоматизированных систем", "id": 20},
        "room": {
            "name": "А-10",
            "id": 23,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 3,
        "week": 1,
        "is_usual_place": True,
        "id": 80,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Петухов А.М.", "id": 32}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Проектирование и разработка автоматизированных систем реального времени",
            "id": 17,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [2, 1],
        "every_week": False,
    },
    {
        "day_of_week": 3,
        "week": 1,
        "is_usual_place": True,
        "id": 81,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Петухов А.М.", "id": 32}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Проектирование и разработка автоматизированных систем реального времени",
            "id": 17,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [2, 1],
        "every_week": False,
    },
    {
        "day_of_week": 3,
        "week": 2,
        "is_usual_place": True,
        "id": 82,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Белова К.И.", "id": 36}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {"name": "Дизайн интерфейсов систем управления", "id": 19},
        "room": {
            "name": "И-204-Б",
            "id": 24,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 3,
        "week": 1,
        "is_usual_place": True,
        "id": 83,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Юрченков И.А.", "id": 37}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Технологии и инструментарий анализа больших данных",
            "id": 21,
        },
        "room": {
            "name": "Г-426",
            "id": 25,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 3,
        "week": 2,
        "is_usual_place": True,
        "id": 84,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Юрченков И.А.", "id": 37}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Технологии и инструментарий анализа больших данных",
            "id": 21,
        },
        "room": {
            "name": "Г-426",
            "id": 25,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 3,
        "week": 1,
        "is_usual_place": True,
        "id": 85,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Серебрянкин В.А.", "id": 38}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {"name": "Моделирование автоматизированных систем", "id": 20},
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [3, 5, 7, 9, 11, 13, 15, 17],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 3,
        "week": 2,
        "is_usual_place": True,
        "id": 86,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Серебрянкин В.А.", "id": 38}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {"name": "Моделирование автоматизированных систем", "id": 20},
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 4,
        "week": 1,
        "is_usual_place": True,
        "id": 87,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Руднева Л.Ю.", "id": 39}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Автоматизация технологических процессов и производств",
            "id": 22,
        },
        "room": {
            "name": "А-177-1",
            "id": 11,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [1, 3, 5, 7, 9, 11, 13, 15],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 4,
        "week": 2,
        "is_usual_place": True,
        "id": 88,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Руднева Л.Ю.", "id": 39}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Автоматизация технологических процессов и производств",
            "id": 22,
        },
        "room": {
            "name": "А-177-1",
            "id": 11,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 4,
        "week": 1,
        "is_usual_place": True,
        "id": 89,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Руднева Л.Ю.", "id": 39}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Автоматизация технологических процессов и производств",
            "id": 22,
        },
        "room": {
            "name": "А-177-1",
            "id": 11,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [1, 3, 5, 7, 9, 11, 13, 15],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 4,
        "week": 2,
        "is_usual_place": True,
        "id": 90,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Берберова М.А.", "id": 40}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Надежность и диагностика автоматизированных систем",
            "id": 23,
        },
        "room": {
            "name": "А-177",
            "id": 26,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 4,
        "week": 1,
        "is_usual_place": True,
        "id": 91,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Берберова М.А.", "id": 40}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Надежность и диагностика автоматизированных систем",
            "id": 23,
        },
        "room": {
            "name": "А-177",
            "id": 26,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [1, 3, 5, 7, 9, 11, 13, 15],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 4,
        "week": 2,
        "is_usual_place": True,
        "id": 92,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Берберова М.А.", "id": 40}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Надежность и диагностика автоматизированных систем",
            "id": 23,
        },
        "room": {
            "name": "А-177",
            "id": 26,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 4,
        "week": 1,
        "is_usual_place": True,
        "id": 93,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Корнеев М.С.", "id": 41}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Автоматизация технологических процессов и производств",
            "id": 22,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [1, 5, 9, 13],
        "subgroups": [1],
        "every_week": False,
    },
    {
        "day_of_week": 4,
        "week": 2,
        "is_usual_place": True,
        "id": 94,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Баев И.Б.", "id": 42}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Автоматизация технологических процессов и производств",
            "id": 22,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [2, 6, 10, 14],
        "subgroups": [2],
        "every_week": False,
    },
    {
        "day_of_week": 4,
        "week": 1,
        "is_usual_place": True,
        "id": 95,
        "call": {"call_num": 5, "begin_time": "16:20", "end_time": "17:50", "id": 5},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Корнеев М.С.", "id": 41}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Автоматизация технологических процессов и производств",
            "id": 22,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [1, 5, 9, 13],
        "subgroups": [1],
        "every_week": False,
    },
    {
        "day_of_week": 4,
        "week": 2,
        "is_usual_place": True,
        "id": 96,
        "call": {"call_num": 5, "begin_time": "16:20", "end_time": "17:50", "id": 5},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Баев И.Б.", "id": 42}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Автоматизация технологических процессов и производств",
            "id": 22,
        },
        "room": {
            "name": "В-108-1",
            "id": 20,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [2, 6, 10, 14],
        "subgroups": [2],
        "every_week": False,
    },
    {
        "day_of_week": 5,
        "week": 1,
        "is_usual_place": True,
        "id": 97,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Курнасов Е.В.", "id": 43}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Технические средства автоматизации и управления",
            "id": 24,
        },
        "room": {
            "name": "А-17",
            "id": 27,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [1, 3, 5, 7, 9, 11, 13, 15],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 5,
        "week": 2,
        "is_usual_place": True,
        "id": 98,
        "call": {"call_num": 3, "begin_time": "12:40", "end_time": "14:10", "id": 3},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Митин М.П.", "id": 9}],
        "lesson_type": {"short_name": "лк", "name": "Лекция", "id": 1},
        "discipline": {
            "name": "Технологии и инструментарий анализа больших данных",
            "id": 21,
        },
        "room": {
            "name": "А-17",
            "id": 27,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
            {
                "name": "ИАБО-02-19",
                "year": 3,
                "id": 4,
                "degree": {"name": "Бакалавриат", "id": 1},
            },
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 5,
        "week": 1,
        "is_usual_place": True,
        "id": 99,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Курнасов Е.В.", "id": 43}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Технические средства автоматизации и управления",
            "id": 24,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [1, 3, 5, 7, 9, 11, 13, 15],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 5,
        "week": 2,
        "is_usual_place": True,
        "id": 100,
        "call": {"call_num": 4, "begin_time": "14:20", "end_time": "15:50", "id": 4},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Курнасов Е.В.", "id": 43}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Технические средства автоматизации и управления",
            "id": 24,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 5,
        "week": 1,
        "is_usual_place": True,
        "id": 101,
        "call": {"call_num": 5, "begin_time": "16:20", "end_time": "17:50", "id": 5},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Юрченков И.А.", "id": 37}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Технологии и инструментарий анализа больших данных",
            "id": 21,
        },
        "room": {
            "name": "Г-413",
            "id": 28,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [1, 3, 5],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 5,
        "week": 2,
        "is_usual_place": True,
        "id": 102,
        "call": {"call_num": 5, "begin_time": "16:20", "end_time": "17:50", "id": 5},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Юрченков И.А.", "id": 37}],
        "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
        "discipline": {
            "name": "Технологии и инструментарий анализа больших данных",
            "id": 21,
        },
        "room": {
            "name": "Г-413",
            "id": 28,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [2, 4, 6],
        "subgroups": [],
        "every_week": False,
    },
    {
        "day_of_week": 6,
        "week": 1,
        "is_usual_place": True,
        "id": 103,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Огорельцев Р.М.", "id": 33}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Технические средства автоматизации и управления",
            "id": 24,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [1, 3, 5, 7, 9, 11, 13, 15],
        "subgroups": [1],
        "every_week": False,
    },
    {
        "day_of_week": 6,
        "week": 2,
        "is_usual_place": True,
        "id": 104,
        "call": {"call_num": 1, "begin_time": "9:00", "end_time": "10:30", "id": 1},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Дергунов А.А.", "id": 44}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Технические средства автоматизации и управления",
            "id": 24,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
    {
        "day_of_week": 6,
        "week": 1,
        "is_usual_place": True,
        "id": 105,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Огорельцев Р.М.", "id": 33}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Технические средства автоматизации и управления",
            "id": 24,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [1, 3, 5, 7, 9, 11, 13, 15],
        "subgroups": [1],
        "every_week": False,
    },
    {
        "day_of_week": 6,
        "week": 2,
        "is_usual_place": True,
        "id": 106,
        "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
        "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
        "teachers": [{"name": "Дергунов А.А.", "id": 44}],
        "lesson_type": {"short_name": "лр", "name": "Лабораторная работа", "id": 3},
        "discipline": {
            "name": "Технические средства автоматизации и управления",
            "id": 24,
        },
        "room": {
            "name": "Г-307",
            "id": 21,
            "place": {
                "id": 1,
                "short_name": "В-78",
                "name": "Проспект Вернадского, д.78",
            },
        },
        "groups": [
            {
                "name": "ИАБО-01-19",
                "year": 3,
                "id": 3,
                "degree": {"name": "Бакалавриат", "id": 1},
            }
        ],
        "specific_weeks": [],
        "subgroups": [],
        "every_week": True,
    },
]
first_lesson = {
    "day_of_week": 1,
    "week": 2,
    "is_usual_place": False,
    "id": 1,
    "call": {"call_num": 2, "begin_time": "10:40", "end_time": "12:10", "id": 2},
    "period": {"short_name": "semester", "name": "Учебный семестр", "id": 1},
    "teachers": [{"name": "Милкина Е.В.", "id": 1}],
    "lesson_type": {"short_name": "пр", "name": "Практическое занятие", "id": 2},
    "discipline": {"name": "Правоведение", "id": 1},
    "room": {
        "name": "А-401",
        "id": 1,
        "place": {"id": 4, "short_name": "МП-1", "name": "Малая Пироговская, д.1"},
    },
    "groups": [
        {
            "name": "ИВБО-01-21",
            "year": 1,
            "id": 1,
            "degree": {"name": "Бакалавриат", "id": 1},
        }
    ],
    "specific_weeks": [],
    "subgroups": [],
    "every_week": True,
}

lessons = [first_lesson, iabo_01_19_lessons]
