"""empty message

Revision ID: 040e28fb44ca
Revises: 
Create Date: 2022-08-26 00:29:07.613542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040e28fb44ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_num', sa.Integer(), nullable=True),
    sa.Column('begin_time', sa.String(length=16), nullable=True),
    sa.Column('end_time', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_begin_time'), 'call', ['begin_time'], unique=True)
    op.create_index(op.f('ix_call_end_time'), 'call', ['end_time'], unique=True)
    op.create_table('degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_degree_name'), 'degree', ['name'], unique=True)
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discipline_name'), 'discipline', ['name'], unique=True)
    op.create_table('file_hash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_hash_name'), 'file_hash', ['name'], unique=True)
    op.create_table('institute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_name', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institute_name'), 'institute', ['name'], unique=True)
    op.create_index(op.f('ix_institute_short_name'), 'institute', ['short_name'], unique=True)
    op.create_table('lesson_type',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_type_name'), 'lesson_type', ['name'], unique=True)
    op.create_index(op.f('ix_lesson_type_short_name'), 'lesson_type', ['short_name'], unique=True)
    op.create_table('period',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_name'), 'period', ['name'], unique=True)
    op.create_index(op.f('ix_period_short_name'), 'period', ['short_name'], unique=True)
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_name'), 'place', ['name'], unique=True)
    op.create_index(op.f('ix_place_short_name'), 'place', ['short_name'], unique=True)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_name'), 'teacher', ['name'], unique=True)
    op.create_table('working_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_data_name'), 'working_data', ['name'], unique=True)
    op.create_index(op.f('ix_working_data_value'), 'working_data', ['value'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('degree_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('lesson_type_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('is_usual_place', sa.Boolean(), nullable=True),
    sa.Column('every_week', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['lesson_type_id'], ['lesson_type.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_group',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'group_id')
    )
    op.create_table('lesson_teacher',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'teacher_id')
    )
    op.create_table('specific_week',
    sa.Column('secific_week', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('secific_week', 'lesson_id')
    )
    op.create_table('subgroup',
    sa.Column('subgroup', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('subgroup', 'lesson_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subgroup')
    op.drop_table('specific_week')
    op.drop_table('lesson_teacher')
    op.drop_table('lesson_group')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_working_data_value'), table_name='working_data')
    op.drop_index(op.f('ix_working_data_name'), table_name='working_data')
    op.drop_table('working_data')
    op.drop_index(op.f('ix_teacher_name'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_place_short_name'), table_name='place')
    op.drop_index(op.f('ix_place_name'), table_name='place')
    op.drop_table('place')
    op.drop_index(op.f('ix_period_short_name'), table_name='period')
    op.drop_index(op.f('ix_period_name'), table_name='period')
    op.drop_table('period')
    op.drop_index(op.f('ix_lesson_type_short_name'), table_name='lesson_type')
    op.drop_index(op.f('ix_lesson_type_name'), table_name='lesson_type')
    op.drop_table('lesson_type')
    op.drop_index(op.f('ix_institute_short_name'), table_name='institute')
    op.drop_index(op.f('ix_institute_name'), table_name='institute')
    op.drop_table('institute')
    op.drop_index(op.f('ix_file_hash_name'), table_name='file_hash')
    op.drop_table('file_hash')
    op.drop_index(op.f('ix_discipline_name'), table_name='discipline')
    op.drop_table('discipline')
    op.drop_index(op.f('ix_degree_name'), table_name='degree')
    op.drop_table('degree')
    op.drop_index(op.f('ix_call_end_time'), table_name='call')
    op.drop_index(op.f('ix_call_begin_time'), table_name='call')
    op.drop_table('call')
    # ### end Alembic commands ###
