name: Build docker image and update service on RTUITLab virtual machine

on:
  push:
    branches:
      - $default-branch
    paths-ignore:
      - 'README.md'


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'sqlite:///./sql_app.db'
      APP_SECRET: 'test_secret'
      ROOT_PATH: '/api'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest -s --asyncio-mode=strict
          
  build:
    needs: [ tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker tag $IMAGE_NAME $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.run_number }}
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Update service
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          SERVICE: ${{ env.SERVICE_NAME }}
        with:
          host: ${{ secrets.RTUITLAB_MANAGER_VM_HOST }}
          username: ${{ secrets.RTUITLAB_MANAGER_VM_USERNAME }}
          key: ${{ secrets.RTUITLAB_MANAGER_VM_SSH_KEY }}
          envs: IMAGE,SERVICE
          script: docker service update --image $IMAGE $SERVICE --with-registry-auth