name: tests

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - 'README.md'
      - 'docker-compose*.yml'
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'sqlite:///./sql_app.db'
      APP_SECRET: 'test_secret'
      ROOT_PATH: '/api'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        working-directory: ./web_api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        working-directory: ./web_api
        run: |
          pytest -s --asyncio-mode=strict
